### ISSUE TITLE
《Watch Dogs Legion》(看门狗 : 军团) 源代码泄露 - Jireh 的个人博客

### ISSUE THREAD

**Issue by Jireh012** [Jireh012/solo-blog#63]
https://www.lyile.cn/articles/2020/11/05/1604567653048.html 

 Jireh个人博客记录分享生活、程序、信息的精彩人生

**Comment by hahahha11** [comment]
有没有人下载好啊,有偿购买

**Comment by VI66666** [comment]
> @hahahha11
> 有没有人下载好啊,有偿购买

帖子不是有种子下载吗

**Comment by ageazrael** [comment]
如果是冲着源码去得，可以停了。附上文件列表

链接: https://pan.baidu.com/s/1u-ON5rVqSY1kQhK9RWuT9w 提取码: n2ig

**Comment by DiliracX** [comment]
> @ageazrael
> 如果是冲着源码去得，可以停了。附上文件列表
> 
> 链接: https://pan.baidu.com/s/1u-ON5rVqSY1kQhK9RWuT9w 提取码: n2ig 
啊 这，全是资源文件 吗

**Comment by Liupeter01** [comment]
话说这东西你们有人扫描过了吗，怕真黑客的东西有后门

**Comment by Jireh012** [comment]
> @Liupeter01
> 话说这东西你们有人扫描过了吗，怕真黑客的东西有后门
太大了，都没解压开来，咋扫。不过还真的有可能，毕竟是个勒索软件组织提供的资源

**Comment by Liupeter01** [comment]
我解开分卷压缩的了，但是内层的还在扫描

**Comment by T-rvw** [comment]
有没有老哥愿意再共享一份~ 可请一杯咖啡
